# Generated by Django 5.1.3 on 2024-11-17 15:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled', max_length=255)),
                ('description', models.TextField(default='No description provided')),
                ('author', models.CharField(default='Anonymous', max_length=100)),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
                ('tags', models.CharField(blank=True, default=' ', max_length=200)),
                ('video_url', models.URLField(default='No URL available', max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
